# Optimize EV Charging Load

**Author:** Eleanor Adachi

**Last updated:** 9/24/2024

**Description:** This is a full test of the new EV charging optimization algorithm for all year and multiple combined scenarios for all ~3000 circuits. Run time with 3 combined scenarios and 3 years is ~14 minutes.

In [4]:
# import packages
import datetime as dt
import itertools
import json
import matplotlib.pyplot as plt
import pandas as pd

from optimize_ev_load import *

In [8]:
# INPUTS

# read combined scenarios to include in analysis
with open(r'..\parameters\combined_scenarios.json') as json_file:
    combined_sc_dict = json.load(json_file)

# set up list of years
# # option 1: specify years (see option 2 later)
# yr_ls = [2030]

# specify limit type
feedlim_type = 'limit_b_md_kw'

Type: <class 'dict'>

In [16]:
list(filter(lambda x: not(x.startswith('_')), combined_sc_dict['B'].keys()))

['EVres', 'EVcom', 'RE']

In [3]:
# read in addload
addload_all = pd.read_csv(r'..\data\addload.csv')

# read in feedlim
feedlim_all = pd.read_csv(r'..\data\feedlim.csv')

In [4]:
# option 2: get all unique years in addload
# WARNING - this will overwrite yr_ls defined previously
ldinc_cols = [x for x in list(addload_all.columns) if x.startswith('ldinc')]
yr_ls = list(set(map(lambda x: int(x.split('_')[2]), ldinc_cols)))
yr_ls.sort()

In [5]:
# initialize newload_all DataFrame
addload_base_cols = ['feeder_id', 'month', 'hour', 'mhid']
newload_all = addload_all[ addload_base_cols ]

# initialize gn_kw_all DataFrame
gn_kw_all = addload_all[['feeder_id']]
gn_kw_all = gn_kw_all.drop_duplicates().reset_index(drop=True)

In [6]:
# filter feedlim
feedlim = feedlim_all[['feeder_id', 'month', 'hour', feedlim_type]]

# rename columns
feedlim = feedlim.rename(columns={feedlim_type: 'limit_kw'})

In [7]:
# start time
start_dt = dt.datetime.now()

# iterate across years and scenarios
for sc_id in combined_sc_dict.keys():
    print('Combined Scenario: ',sc_id)
    for yr in yr_ls:
        print('Year: ',yr)
        
        # select load-scenario dictionary based on combined scenario ID
        load_sc_dict = combined_sc_dict[sc_id]

        # filter & rename columns
        keep_cols = addload_base_cols.copy() # need to copy to "reset" the list
        rename_col_dict = {}
        # for load_type in load_sc_dict.keys():
        load_type_ls = list(filter(lambda x: not(x.startswith('_')), load_sc_dict.keys())) # exclude keys that start with underscore
        for load_type in load_type_ls:
            sc_num = load_sc_dict[load_type]
            load_sc_yr_col = f'ldinc_{load_type}{sc_num}_{yr}_kW'
            keep_cols.append(load_sc_yr_col)
            rename_col_dict[load_sc_yr_col] = load_type
        addload = addload_all[ keep_cols ]
        addload = addload.rename(columns=rename_col_dict)

        # filter out NaN
        addload = addload.dropna()
        
        # get list of unique load types
        # other_loads = list(set(load_sc_dict.keys()) - set(['EVres', 'EVcom']))
        other_loads = list(set(load_type_ls) - set(['EVres', 'EVcom']))
        # combine other loads
        addload['other'] = addload[ other_loads ].sum(axis=1)
        # drop other loads
        addload = addload.drop(columns=other_loads)

        # merge addload and feedlim; INNER merge to ensure that data is available
        input_df = pd.merge(addload, feedlim, how='inner', on=['feeder_id', 'month', 'hour'])

        # compute pre-optimization hourly grid need
        input_df['hourly_need'] = input_df['EVres'] + input_df['EVcom'] + input_df['other'] - input_df['limit_kw']

        # create grid need dataframe
        # NOTE: Positive "grid need" means that loads exceed limits (i.e. upgrades required), negative "grid need" means that there is "headroom"
        gn_kw_df = pd.pivot_table(input_df, values='hourly_need', index='feeder_id', aggfunc='max')
        gn_kw_df = gn_kw_df.reset_index()
        gn_kw_df = gn_kw_df.rename(columns={'hourly_need':'gn_kw'})
        
        # count number of circuits
        feednum = len(input_df['feeder_id'].unique())
        print('Number of feeders included in optimization: ', feednum)
        
        # optimize EV charging
        output_df, gn_kw_opt_df = optimize_ev_load(input_df)

        # compute post-optimization hourly grid need
        # NOTE: Not used in this script, only need for plotting
        # output_df['hourly_need_opt'] = output_df['EVres_opt'] + output_df['EVcom_opt'] + output_df['other'] - output_df['limit_kw']

        # save to newload
        newload = output_df[['feeder_id', 'month', 'hour', 'mhid', 'EVres_opt', 'EVcom_opt']]
        # TODO: Use sc_num or sc_id? Using sc_id for now
        newload = newload.rename(columns={'EVres_opt': f'ldinc_EVres{sc_id}_{yr}_kW_opt', 'EVcom_opt': f'ldinc_EVcom{sc_id}_{yr}_kW_opt'})
        # EVres_sc_num = load_sc_dict['EVres']
        # EVcom_sc_num = load_sc_dict['EVcom']
        # newload = newload.rename(columns={'EVres_opt': f'ldinc_EVres{EVres_sc_num}_{yr}_kW_opt', 'EVcom_opt': f'ldinc_EVcom{EVcom_sc_num}_{yr}_kW_opt'})
        newload_all = pd.merge(newload_all, newload, how='outer', on=['feeder_id', 'month', 'hour', 'mhid'])

        # merge gn_kw_df and gn_kw_opt_df
        gn_kw_df = pd.merge(gn_kw_df, gn_kw_opt_df, how='outer', on='feeder_id')

        # zero out any negative values
        gn_kw_df['gn_kw'] = gn_kw_df['gn_kw'].clip(lower=0)
        gn_kw_df['gn_kw_opt'] = gn_kw_df['gn_kw_opt'].clip(lower=0)
        
        # add gn_kw_df to gn_kw_all
        gn_kw_df = gn_kw_df.rename(columns={'gn_kw': f'gn_{sc_id}_{yr}_kW', 'gn_kw_opt': f'gn_{sc_id}_{yr}_kW_opt'})
        gn_kw_all = pd.merge(gn_kw_all, gn_kw_df, how='outer', on='feeder_id')

# end time
end_dt = dt.datetime.now()

print('Elapsed time: ', end_dt - start_dt)

Combined Scenario:  B
Year:  2030
Number of feeders included in optimization:  1965

C:\Users\elean\OneDrive_relink\OneDrive\Documents\UC Berkeley\ERG Masters Project\EV infrastructure\ccai-dac-grid\scripts\optimize_ev_load.py:114: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_df0], axis=0)

Year:  2040
Number of feeders included in optimization:  1965

C:\Users\elean\OneDrive_relink\OneDrive\Documents\UC Berkeley\ERG Masters Project\EV infrastructure\ccai-dac-grid\scripts\optimize_ev_load.py:114: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_df0], axis=0)

Year:  2050
Number of feeders included in optimization:  1965

C:\Users\elean\OneDrive_relink\OneDrive\Documents\UC Berkeley\ERG Masters Project\EV infrastructure\ccai-dac-grid\scripts\optimize_ev_load.py:114: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_df0], axis=0)

Combined Scenario:  C
Year:  2030
Number of feeders included in optimization:  1965

C:\Users\elean\OneDrive_relink\OneDrive\Documents\UC Berkeley\ERG Masters Project\EV infrastructure\ccai-dac-grid\scripts\optimize_ev_load.py:114: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_df0], axis=0)

Year:  2040
Number of feeders included in optimization:  1965

C:\Users\elean\OneDrive_relink\OneDrive\Documents\UC Berkeley\ERG Masters Project\EV infrastructure\ccai-dac-grid\scripts\optimize_ev_load.py:114: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_df0], axis=0)

Year:  2050
Number of feeders included in optimization:  1965

C:\Users\elean\OneDrive_relink\OneDrive\Documents\UC Berkeley\ERG Masters Project\EV infrastructure\ccai-dac-grid\scripts\optimize_ev_load.py:114: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_df0], axis=0)

Combined Scenario:  D
Year:  2030
Number of feeders included in optimization:  1965

C:\Users\elean\OneDrive_relink\OneDrive\Documents\UC Berkeley\ERG Masters Project\EV infrastructure\ccai-dac-grid\scripts\optimize_ev_load.py:114: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_df0], axis=0)

Year:  2040
Number of feeders included in optimization:  1965

C:\Users\elean\OneDrive_relink\OneDrive\Documents\UC Berkeley\ERG Masters Project\EV infrastructure\ccai-dac-grid\scripts\optimize_ev_load.py:114: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_df0], axis=0)

Year:  2050
Number of feeders included in optimization:  1965

C:\Users\elean\OneDrive_relink\OneDrive\Documents\UC Berkeley\ERG Masters Project\EV infrastructure\ccai-dac-grid\scripts\optimize_ev_load.py:114: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_df0], axis=0)

Elapsed time:  0:12:35.814045

In [8]:
newload_all.tail()

,feeder_id,month,hour,mhid,ldinc_EVresB_2030_kW_opt,ldinc_EVcomB_2030_kW_opt,ldinc_EVresB_2040_kW_opt,ldinc_EVcomB_2040_kW_opt,ldinc_EVresB_2050_kW_opt,ldinc_EVcomB_2050_kW_opt,...,ldinc_EVresC_2040_kW_opt,ldinc_EVcomC_2040_kW_opt,ldinc_EVresC_2050_kW_opt,ldinc_EVcomC_2050_kW_opt,ldinc_EVresD_2030_kW_opt,ldinc_EVcomD_2030_kW_opt,ldinc_EVresD_2040_kW_opt,ldinc_EVcomD_2040_kW_opt,ldinc_EVresD_2050_kW_opt,ldinc_EVcomD_2050_kW_opt
880099,255451103,12,19,284,370.134,24.257,740.268,48.515,1480.536,97.029,...,534.315,88.376,1068.631,176.751,204.317,55.104,408.633,110.207,817.267,220.415
880100,255451103,12,20,285,281.047,16.750,562.094,33.501,1124.189,67.002,...,400.372,52.860,800.745,105.719,153.970,32.293,307.940,64.587,615.880,129.174
880101,255451103,12,21,286,211.808,11.819,423.617,23.639,847.234,47.277,...,299.314,35.278,598.627,70.556,116.820,19.603,233.641,39.206,467.282,78.412
880102,255451103,12,22,287,168.653,6.970,337.305,13.939,674.611,27.878,...,238.574,18.245,477.148,36.491,96.143,10.976,192.285,21.953,384.571,43.905
880103,255451103,12,23,288,134.191,4.921,268.383,9.841,536.765,19.682,...,189.732,12.015,379.464,24.029,76.166,6.903,152.332,13.807,304.664,27.613

In [9]:
gn_kw_all.tail()

,feeder_id,gn_B_2030_kW,gn_B_2030_kW_opt,gn_B_2040_kW,gn_B_2040_kW_opt,gn_B_2050_kW,gn_B_2050_kW_opt,gn_C_2030_kW,gn_C_2030_kW_opt,gn_C_2040_kW,gn_C_2040_kW_opt,gn_C_2050_kW,gn_C_2050_kW_opt,gn_D_2030_kW,gn_D_2030_kW_opt,gn_D_2040_kW,gn_D_2040_kW_opt,gn_D_2050_kW,gn_D_2050_kW_opt
3050,255391101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3051,255391102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3052,255391103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3053,255451102,166.566,0.0,3053.828,2564.859,6256.875,4474.546,0.0,0.0,2478.374,2478.374,4789.068,4301.577,0.0,0.0,2430.886,2430.886,4206.600,4206.600
3054,255451103,127.457,0.0,2692.148,2044.316,5640.917,3662.917,0.0,0.0,2000.060,1855.856,4256.742,3285.997,0.0,0.0,1737.572,1737.572,3376.537,3049.429

In [10]:
# save results
newload_all.to_csv(r'..\results\newload.csv', index=False)
gn_kw_all.to_csv(r'..\results\gridneed.csv', index=False)